export const FRIENDS_LIST_REQ = "FRIENDS_LIST_REQ"
export const FRIENDS_LIST_SUC = "FRIENDS_LIST_SUC"
export const FRIENDS_LIST_FAI = "FRIENDS_LIST_FAI"

export const FRIENDS_SEARCH_REQ = "FRIENDS_SEARCH_REQ"
export const FRIENDS_SEARCH_SUC = "FRIENDS_SEARCH_SUC"
export const FRIENDS_SEARCH_FAI = "FRIENDS_SEARCH_FAI"






