export const FRIENDS_LIST_REQ = "FRIENDS_LIST_REQ"
export const FRIENDS_LIST_SUC = "FRIENDS_LIST_SUC"
export const FRIENDS_LIST_FAI = "FRIENDS_LIST_FAI"

export const FRIENDS_SEARCH_REQ = "FRIENDS_SEARCH_REQ"
export const FRIENDS_SEARCH_SUC = "FRIENDS_SEARCH_SUC"
export const FRIENDS_SEARCH_FAI = "FRIENDS_SEARCH_FAI"

export const UPDATE_FRIENDS_REQ = "UPDATE_FRIENDS_REQ"
export const UPDATE_FRIENDS_SUC = "UPDATE_FRIENDS_SUC"
export const UPDATE_FRIENDS_FAI = "UPDATE_FRIENDS_FAI"





